//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/PinBallInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PinBallInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PinBallInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PinBallInput"",
    ""maps"": [
        {
            ""name"": ""PinBall"",
            ""id"": ""de56f548-2f6e-4b2d-af40-3b2a85bec6d3"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""82005f07-1553-4870-b953-8d7ebf18aa07"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""9c469387-24ff-4672-ba34-8e2fd8c1957e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponNext"",
                    ""type"": ""Button"",
                    ""id"": ""f8f14e9b-89d3-4785-bca5-c42f788b3061"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""WeaponPrevious"",
                    ""type"": ""Button"",
                    ""id"": ""8d7491de-650f-48d0-bac6-cb810ba73292"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""d3fc78e0-079b-4f9e-adb0-0e611ac96db7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""66394890-2755-46da-82f8-963bd8182bbc"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1f0ee6a3-1c1e-4cc1-8854-9f3e24efc03d"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""132dea15-e1be-47f7-9db7-5fc26ddf56a6"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""7fd31897-a68f-43a5-bca0-7b088711a140"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""LeftStick"",
                    ""id"": ""e208e2bf-fe5a-4158-ba7d-1314be2da0f2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0b6b6c4a-3486-4d72-99ea-de2a18c2c953"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d825c5e4-f35d-4218-880b-85a9659e95c0"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5f206cb3-de0f-42e0-8646-0e351ff2a0c9"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a78d238f-6252-4047-9e67-a8edfdf2c5a7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0f50f9e6-5b54-4d0b-a7a0-fc84732ab806"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d663566-4aef-4321-8a74-eed8013cdd57"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""516bc08d-4502-49d1-912c-e33fae8821ff"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""763d4f86-92de-40e2-9cf3-b23f00eaff86"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponNext"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d5695fc-2bf2-4491-a560-0bcdd3ddea04"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""WeaponPrevious"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PinBall
        m_PinBall = asset.FindActionMap("PinBall", throwIfNotFound: true);
        m_PinBall_Movement = m_PinBall.FindAction("Movement", throwIfNotFound: true);
        m_PinBall_Shoot = m_PinBall.FindAction("Shoot", throwIfNotFound: true);
        m_PinBall_WeaponNext = m_PinBall.FindAction("WeaponNext", throwIfNotFound: true);
        m_PinBall_WeaponPrevious = m_PinBall.FindAction("WeaponPrevious", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PinBall
    private readonly InputActionMap m_PinBall;
    private IPinBallActions m_PinBallActionsCallbackInterface;
    private readonly InputAction m_PinBall_Movement;
    private readonly InputAction m_PinBall_Shoot;
    private readonly InputAction m_PinBall_WeaponNext;
    private readonly InputAction m_PinBall_WeaponPrevious;
    public struct PinBallActions
    {
        private @PinBallInput m_Wrapper;
        public PinBallActions(@PinBallInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PinBall_Movement;
        public InputAction @Shoot => m_Wrapper.m_PinBall_Shoot;
        public InputAction @WeaponNext => m_Wrapper.m_PinBall_WeaponNext;
        public InputAction @WeaponPrevious => m_Wrapper.m_PinBall_WeaponPrevious;
        public InputActionMap Get() { return m_Wrapper.m_PinBall; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PinBallActions set) { return set.Get(); }
        public void SetCallbacks(IPinBallActions instance)
        {
            if (m_Wrapper.m_PinBallActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PinBallActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PinBallActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PinBallActionsCallbackInterface.OnMovement;
                @Shoot.started -= m_Wrapper.m_PinBallActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_PinBallActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_PinBallActionsCallbackInterface.OnShoot;
                @WeaponNext.started -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponNext;
                @WeaponNext.performed -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponNext;
                @WeaponNext.canceled -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponNext;
                @WeaponPrevious.started -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponPrevious;
                @WeaponPrevious.performed -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponPrevious;
                @WeaponPrevious.canceled -= m_Wrapper.m_PinBallActionsCallbackInterface.OnWeaponPrevious;
            }
            m_Wrapper.m_PinBallActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @WeaponNext.started += instance.OnWeaponNext;
                @WeaponNext.performed += instance.OnWeaponNext;
                @WeaponNext.canceled += instance.OnWeaponNext;
                @WeaponPrevious.started += instance.OnWeaponPrevious;
                @WeaponPrevious.performed += instance.OnWeaponPrevious;
                @WeaponPrevious.canceled += instance.OnWeaponPrevious;
            }
        }
    }
    public PinBallActions @PinBall => new PinBallActions(this);
    public interface IPinBallActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnWeaponNext(InputAction.CallbackContext context);
        void OnWeaponPrevious(InputAction.CallbackContext context);
    }
}
